const actions = {
  ADD_ASADO: 'ADD_ASADO',
  EDIT_ASADO: 'EDIT_ASADO',
  REMOVE_ASADO: 'REMOVE_ASADO',
  SET_FORM_VISIBLE: 'SET_FORM_VISIBLE',
  SET_FORM_HIDDEN: 'SET_FORM_HIDDEN',
  SET_PAGE: 'SET_PAGE',
  UNSET_PAGE: 'UNSET_PAGE'
}

export default actions
